import type { MissionTimelineEventRecord } from './dashboard-types';

export const dashboardMissionTimelineEvents: MissionTimelineEventRecord[] = [
  {
    id: 'mission-003-event-001',
    missionId: 'mission-003',
    actorName: 'Ari',
    actorRole: 'Coordinator',
    action: 'opened Mission 002 and confirmed the replay scope',
    timestamp: '2026-05-26T07:52:00.000Z',
    sequenceIndex: 1,
    sourceLabel: 'repository-backed live source',
  },
  {
    id: 'mission-003-event-002',
    missionId: 'mission-003',
    actorName: 'Mira',
    actorRole: 'Backend Developer',
    action: 'mapped the read-only event contract',
    timestamp: '2026-05-26T07:53:00.000Z',
    sequenceIndex: 2,
    sourceLabel: 'repository-backed live source',
    parallelGroupId: 'mission-003-parallel-01',
    parallelOrder: 0,
    parallelSize: 2,
  },
  {
    id: 'mission-003-event-003',
    missionId: 'mission-003',
    actorName: 'Theo',
    actorRole: 'Frontend Developer',
    action: 'drafted the live timeline rendering states',
    timestamp: '2026-05-26T07:53:00.000Z',
    sequenceIndex: 3,
    sourceLabel: 'repository-backed live source',
    parallelGroupId: 'mission-003-parallel-01',
    parallelOrder: 1,
    parallelSize: 2,
  },
  {
    id: 'mission-003-event-004',
    missionId: 'mission-003',
    actorName: 'Nia',
    actorRole: 'QA',
    action: 'checked ordering, lag, and stale-state handling',
    timestamp: '2026-05-26T07:54:00.000Z',
    sequenceIndex: 4,
    sourceLabel: 'repository-backed live source',
  },
  {
    id: 'mission-003-event-005',
    missionId: 'mission-003',
    actorName: null,
    actorRole: null,
    action: null,
    timestamp: '2026-05-26T07:55:00.000Z',
    sequenceIndex: 5,
    sourceLabel: 'repository-backed live source',
    freshness: 'partial',
  },
];
